all: lab11 sol1 sol2

lab11: lab11.c 
	gcc lab11.c -g -o lab11

sol1: lab11_sol1.c 
	gcc lab11_sol1.c -g -o sol1	

sol2: lab11_sol2.c 
	gcc lab11_sol2.c -g -o sol2

.PHONY: clean

clean:
	rm lab11 sol1 sol2
